name: Publish

on:
  push:
    tags:
      - '*'
  push:
    branches:
      - "test-workflow"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: yaf
            asset_name: yaf-linux-amd64
          - os: windows-latest
            artifact_name: yaf.exe
            asset_name: yaf-windows-amd64
          - os: macos-latest
            artifact_name: yaf
            asset_name: yaf-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: go build yaf .
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}